#!/usr/bin/env python3

import logging
from simpleMediaCenter import SimpleMediaCenter

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    logging.info('Starting Simple Media Center...')
    smc = SimpleMediaCenter()
    smc.run()
    logging.shutdown()
