#!/usr/bin/env python3

import logging
from simpleMediaCenter import SimpleMediaCenter, parseArgs

if __name__ == "__main__":
    args = parseArgs()
    if(args.verbosity):
        logging.basicConfig(level=args.verbosity)
    else:
        logging.basicConfig(level=logging.INFO)
    logging.info('Starting Simple Media Center...')
    smc = SimpleMediaCenter()
    smc.run()
    logging.info('Stopped Simple Media Center...')
    logging.shutdown()
